# Configuration file for IMU-only LightGBM baseline model

# Data paths
data:
  train_path: "cmi-detect-behavior-with-sensor-data/train.csv"
  train_demographics_path: "cmi-detect-behavior-with-sensor-data/train_demographics.csv"
  test_path: "cmi-detect-behavior-with-sensor-data/test.csv"
  test_demographics_path: "cmi-detect-behavior-with-sensor-data/test_demographics.csv"

# Training parameters
training:
  seed: 42
  n_folds: 5
  test_size: 0.2

# Feature extraction
features:
  acc_cols: ["acc_x", "acc_y", "acc_z"]
  rot_cols: ["rot_w", "rot_x", "rot_y", "rot_z"]
  use_world_acceleration: true
  segment_count: 3  # 分割数（beginning, middle, end）

# LightGBM parameters
lgbm:
  objective: "multiclass"
  n_estimators: 1024
  max_depth: 8
  learning_rate: 0.025
  colsample_bytree: 0.5
  num_leaves: 20
  reg_alpha: 0.1
  reg_lambda: 0.1
  subsample: 0.5
  early_stopping_rounds: 100
  eval_metric: "multi_logloss"
  verbose: -1
  n_jobs: -1

# Output settings
output:
  model_dir: "results/models"
  log_dir: "results/logs"
  plot_dir: "results/plots"
  save_oof_predictions: true
  save_feature_importance: true